# This task enables Percona-Server-84 (ps84) main repository, installs and starts percona-server.

# Enable ps84 main repo and install ps84
  - name: include tasks for enabling ps84 main repo
    include_tasks: ../tasks/enable_ps84_main_repo.yml

  - name: include tasks for installing ps84 packages
    vars:
      packages: percona-server-server
    include_tasks:
      file: ../tasks/install_ps84.yml
      apply:
        environment:
          PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

# Start mysql service
  - name: start mysql service on Debian
    service:
      name: mysql
      state: started
    when: ansible_os_family == "Debian"

  - name: start mysql service on CentOS
    systemd:
      name: mysql
      state: started
    when: ansible_os_family == "RedHat"

# On Centos ps is started with random root password. Change ps root password and create cnf with new client password on centos.
  - name: set root password on CentOS
    command: ../setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: copy .my.cnf with credentials on CentOS
    template: src=../templates/my_57.j2
              dest=/root/.my.cnf
              mode=0640 owner=root group=root
    when: ansible_os_family == "RedHat"

